/**
 * 40-Week Gestational Timeline & Development Guide
 * Provides weekly fetal growth, size comparisons, maternal bodily changes,
 * and key DOH/clinical milestones.
 */

export interface WeekMilestone {
  week: number;
  trimester: 1 | 2 | 3;
  sizeComparison: string;
  approxWeight: string;
  approxLength: string;
  babyDevelopment: string;
  momExperience: string;
  clinicalMilestone?: string;
}

export const PREGNANCY_WEEKS: WeekMilestone[] = [
  {
    week: 1,
    trimester: 1,
    sizeComparison: "Microscopic (Pre-conception cycle)",
    approxWeight: "< 1g",
    approxLength: "< 1 mm",
    babyDevelopment: "Your body is preparing for ovulation and conception.",
    momExperience: "Your menstrual cycle begins. Take daily Folic Acid.",
    clinicalMilestone: "Start prenatal multivitamin with 400mcg Folic Acid.",
  },
  {
    week: 2,
    trimester: 1,
    sizeComparison: "Microscopic",
    approxWeight: "< 1g",
    approxLength: "< 1 mm",
    babyDevelopment: "Ovulation occurs and fertilization may take place.",
    momExperience: "Hormone levels shift as the uterine lining thickens.",
  },
  {
    week: 3,
    trimester: 1,
    sizeComparison: "Pinhead",
    approxWeight: "< 1g",
    approxLength: "0.1 mm",
    babyDevelopment: "The fertilized egg (blastocyst) travels to the uterus and implants.",
    momExperience: "You might experience light implantation spotting.",
  },
  {
    week: 4,
    trimester: 1,
    sizeComparison: "Poppy Seed",
    approxWeight: "< 1g",
    approxLength: "1 mm",
    babyDevelopment: "The amniotic sac and placenta begin to form.",
    momExperience: "Missed period; home pregnancy test shows positive result.",
    clinicalMilestone: "Positive urine pregnancy test; register at your BHS/RHU.",
  },
  {
    week: 5,
    trimester: 1,
    sizeComparison: "Apple Seed",
    approxWeight: "< 1g",
    approxLength: "2 mm",
    babyDevelopment: "Baby's neural tube (brain and spinal cord) develops rapidly.",
    momExperience: "Mild fatigue, tender breasts, and frequent urination.",
  },
  {
    week: 6,
    trimester: 1,
    sizeComparison: "Sweet Pea",
    approxWeight: "< 1g",
    approxLength: "4 - 5 mm",
    babyDevelopment: "Baby's tiny heart begins beating at 100-160 beats per minute.",
    momExperience: "Morning sickness and food aversions may begin.",
  },
  {
    week: 7,
    trimester: 1,
    sizeComparison: "Blueberry",
    approxWeight: "< 1g",
    approxLength: "10 mm",
    babyDevelopment: "Arm and leg buds emerge; facial features start forming.",
    momExperience: "Heightened sense of smell and mild mood swings.",
  },
  {
    week: 8,
    trimester: 1,
    sizeComparison: "Raspberry",
    approxWeight: "1g",
    approxLength: "1.6 cm",
    babyDevelopment: "Fingers and toes start forming; baby makes tiny spontaneous movements.",
    momExperience: "Uterus is now the size of a grapefruit.",
    clinicalMilestone: "Recommended First Prenatal Visit (1st ANC): Baseline vitals, CBC, Blood Type, Urinalysis.",
  },
  {
    week: 9,
    trimester: 1,
    sizeComparison: "Green Olive",
    approxWeight: "2g",
    approxLength: "2.3 cm",
    babyDevelopment: "All essential organs have begun development; tiny earlobes appear.",
    momExperience: "Digestive slowdown may cause mild bloating or heartburn.",
  },
  {
    week: 10,
    trimester: 1,
    sizeComparison: "Prune",
    approxWeight: "4g",
    approxLength: "3.1 cm",
    babyDevelopment: "Embryonic stage ends; baby is now officially a fetus.",
    momExperience: "Veins on breasts and belly become more visible due to higher blood volume.",
  },
  {
    week: 11,
    trimester: 1,
    sizeComparison: "Lime",
    approxWeight: "7g",
    approxLength: "4.1 cm",
    babyDevelopment: "Baby is kicking and stretching, though still too tiny to feel.",
    momExperience: "Nausea may begin to subside for some mothers.",
  },
  {
    week: 12,
    trimester: 1,
    sizeComparison: "Plum",
    approxWeight: "14g",
    approxLength: "5.4 cm",
    babyDevelopment: "Reflexes develop; baby can open and close fingers and curl toes.",
    momExperience: "Uterus begins rising above pelvic bone; nausea eases.",
    clinicalMilestone: "First Trimester Dating Ultrasound & Tetanus (Td) vaccine assessment.",
  },
  {
    week: 13,
    trimester: 2,
    sizeComparison: "Lemon",
    approxWeight: "23g",
    approxLength: "7.4 cm",
    babyDevelopment: "Vocal cords form; baby has unique fingerprints on fingertips.",
    momExperience: "Welcome to the 2nd Trimester! Energy levels typically rebound.",
  },
  {
    week: 14,
    trimester: 2,
    sizeComparison: "Navel Orange",
    approxWeight: "43g",
    approxLength: "8.7 cm",
    babyDevelopment: "Baby can squint, frown, and make facial expressions.",
    momExperience: "Your baby bump starts becoming visible.",
  },
  {
    week: 15,
    trimester: 2,
    sizeComparison: "Apple",
    approxWeight: "70g",
    approxLength: "10.1 cm",
    babyDevelopment: "Baby's skeleton is hardening from cartilage into bone.",
    momExperience: "Nasal congestion or mild gum sensitivity may occur.",
  },
  {
    week: 16,
    trimester: 2,
    sizeComparison: "Avocado",
    approxWeight: "100g",
    approxLength: "11.6 cm",
    babyDevelopment: "Baby's eyes can make small movements and detect light through eyelids.",
    momExperience: "Glowing skin ('pregnancy glow') from increased circulation.",
    clinicalMilestone: "Fundic height measurement and fetal heart tone check with Doppler.",
  },
  {
    week: 17,
    trimester: 2,
    sizeComparison: "Pomegranate",
    approxWeight: "140g",
    approxLength: "13 cm",
    babyDevelopment: "Fat tissue begins depositing to help keep baby warm.",
    momExperience: "Mild round ligament pain (stretching on belly sides).",
  },
  {
    week: 18,
    trimester: 2,
    sizeComparison: "Bell Pepper",
    approxWeight: "190g",
    approxLength: "14.2 cm",
    babyDevelopment: "Ears are in place; baby can hear mother's heartbeat and outside voices.",
    momExperience: "You may feel gentle butterfly flutters (quickening).",
  },
  {
    week: 19,
    trimester: 2,
    sizeComparison: "Mango",
    approxWeight: "240g",
    approxLength: "15.3 cm",
    babyDevelopment: "Vernix caseosa (protective waxy coating) covers baby's skin.",
    momExperience: "Leg cramps may occur at night; stay well hydrated.",
  },
  {
    week: 20,
    trimester: 2,
    sizeComparison: "Banana",
    approxWeight: "300g",
    approxLength: "25.6 cm",
    babyDevelopment: "Halfway point! Baby is actively practicing swallowing amniotic fluid.",
    momExperience: "Definite fetal movement kicks and flips felt by mom.",
    clinicalMilestone: "2nd ANC Visit: Congenital Anomaly Scan (CAS) ultrasound.",
  },
  {
    week: 21,
    trimester: 2,
    sizeComparison: "Carrot",
    approxWeight: "360g",
    approxLength: "26.7 cm",
    babyDevelopment: "Baby's bone marrow starts producing blood cells.",
    momExperience: "Increased appetite; focus on nutrient-dense meals.",
  },
  {
    week: 22,
    trimester: 2,
    sizeComparison: "Papaya",
    approxWeight: "430g",
    approxLength: "27.8 cm",
    babyDevelopment: "Eyebrows and eyelashes are fully visible; senses develop.",
    momExperience: "Mild swelling in feet after standing; elevate feet when resting.",
  },
  {
    week: 23,
    trimester: 2,
    sizeComparison: "Grapefruit",
    approxWeight: "500g",
    approxLength: "28.9 cm",
    babyDevelopment: "Lungs begin producing surfactant to prepare for breathing air.",
    momExperience: "Braxton Hicks contractions (mild, painless tightenings) may begin.",
  },
  {
    week: 24,
    trimester: 2,
    sizeComparison: "Ear of Corn",
    approxWeight: "600g",
    approxLength: "30 cm",
    babyDevelopment: "Viability milestone! Baby's inner ear is fully formed for balance.",
    momExperience: "Belly button may start popping out as the uterus expands.",
    clinicalMilestone: "3rd ANC Visit: Oral Glucose Tolerance Test (OGTT) for gestational diabetes.",
  },
  {
    week: 25,
    trimester: 2,
    sizeComparison: "Rutabaga",
    approxWeight: "660g",
    approxLength: "34.6 cm",
    babyDevelopment: "Baby responds to touch and sound with purposeful kicks.",
    momExperience: "Thicker hair due to pregnancy hormones.",
  },
  {
    week: 26,
    trimester: 2,
    sizeComparison: "Zucchini",
    approxWeight: "760g",
    approxLength: "35.6 cm",
    babyDevelopment: "Baby's eyes open for the first time and eyelashes flutter.",
    momExperience: "Occasional shortness of breath as uterus presses against diaphragm.",
  },
  {
    week: 27,
    trimester: 2,
    sizeComparison: "Cauliflower",
    approxWeight: "875g",
    approxLength: "36.6 cm",
    babyDevelopment: "Baby has regular sleep and wake cycles and may get hiccups!",
    momExperience: "Rhythmic tapping in belly indicates baby hiccups.",
  },
  {
    week: 28,
    trimester: 3,
    sizeComparison: "Eggplant",
    approxWeight: "1.0 kg",
    approxLength: "37.6 cm",
    babyDevelopment: "Welcome to the 3rd Trimester! Baby's brain tissue multiplies rapidly.",
    momExperience: "Visit your health center every 2 weeks from now on.",
    clinicalMilestone: "3rd Trimester Blood Pressure & Urinalysis check for Pre-Eclampsia.",
  },
  {
    week: 29,
    trimester: 3,
    sizeComparison: "Butternut Squash",
    approxWeight: "1.15 kg",
    approxLength: "38.6 cm",
    babyDevelopment: "Baby's bones absorb large amounts of calcium to harden.",
    momExperience: "Ensure adequate calcium and Vitamin D intake.",
  },
  {
    week: 30,
    trimester: 3,
    sizeComparison: "Cabbage",
    approxWeight: "1.3 kg",
    approxLength: "39.9 cm",
    babyDevelopment: "Baby's eyesight continues to sharpen.",
    momExperience: "Backache may increase; use supportive pillows during sleep.",
    clinicalMilestone: "4th ANC Visit: Establish birth plan, emergency transport, and blood donor.",
  },
  {
    week: 31,
    trimester: 3,
    sizeComparison: "Coconut",
    approxWeight: "1.5 kg",
    approxLength: "41.1 cm",
    babyDevelopment: "Baby can turn head from side to side and tracks rhythms.",
    momExperience: "Frequent bathroom trips as baby presses on bladder.",
  },
  {
    week: 32,
    trimester: 3,
    sizeComparison: "Pineapple",
    approxWeight: "1.7 kg",
    approxLength: "42.4 cm",
    babyDevelopment: "Toenails and fingernails are completely formed.",
    momExperience: "Begin monitoring daily fetal kick counts.",
  },
  {
    week: 33,
    trimester: 3,
    sizeComparison: "Cantaloupe",
    approxWeight: "1.9 kg",
    approxLength: "43.7 cm",
    babyDevelopment: "Baby's immune system receives antibodies from mother.",
    momExperience: "Colostrum (early breast milk) may occasionally leak.",
  },
  {
    week: 34,
    trimester: 3,
    sizeComparison: "Honeydew Melon",
    approxWeight: "2.1 kg",
    approxLength: "45 cm",
    babyDevelopment: "Central nervous system and lungs are maturing rapidly.",
    momExperience: "Review delivery danger signs and pack hospital go-bag.",
    clinicalMilestone: "5th ANC Visit: Danger signs review & PhilHealth MCP document check.",
  },
  {
    week: 35,
    trimester: 3,
    sizeComparison: "Winter Melon",
    approxWeight: "2.4 kg",
    approxLength: "46.2 cm",
    babyDevelopment: "Baby takes up most space in uterus; rolls and stretches replace big kicks.",
    momExperience: "Pelvic pressure increases as baby drops lower.",
  },
  {
    week: 36,
    trimester: 3,
    sizeComparison: "Papaya",
    approxWeight: "2.6 kg",
    approxLength: "47.4 cm",
    babyDevelopment: "Baby sheds lanugo (fine body hair) and vernix coating.",
    momExperience: "Weekly prenatal checkups recommended from Week 36 onward.",
    clinicalMilestone: "6th ANC Visit: Fetal presentation check (Head down / Cephalic).",
  },
  {
    week: 37,
    trimester: 3,
    sizeComparison: "Swiss Chard",
    approxWeight: "2.9 kg",
    approxLength: "48.6 cm",
    babyDevelopment: "Early Term! Baby is considered full term in just a few days.",
    momExperience: "Watch for signs of true labor: regular contractions, bloody show.",
  },
  {
    week: 38,
    trimester: 3,
    sizeComparison: "Leek",
    approxWeight: "3.1 kg",
    approxLength: "49.8 cm",
    babyDevelopment: "Baby has firm grasp reflexes and full head of hair.",
    momExperience: "Breathing becomes easier as baby engages into pelvis ('lightening').",
    clinicalMilestone: "7th ANC Visit: Term assessment & labor signs counseling.",
  },
  {
    week: 39,
    trimester: 3,
    sizeComparison: "Mini Watermelon",
    approxWeight: "3.3 kg",
    approxLength: "50.7 cm",
    babyDevelopment: "Full term! Lungs and brain are completely prepared for outside world.",
    momExperience: "Cervix begins softening and effacing in preparation for delivery.",
  },
  {
    week: 40,
    trimester: 3,
    sizeComparison: "Watermelon",
    approxWeight: "3.5 kg",
    approxLength: "51.2 cm",
    babyDevelopment: "Happy Due Date! Baby is ready to meet mother and family.",
    momExperience: "Stay calm and in contact with your midwife / delivery facility.",
    clinicalMilestone: "8th ANC Visit: Due date review & hospital admission readiness.",
  },
];

export function getWeekMilestone(week: number): WeekMilestone {
  const safeWeek = Math.max(1, Math.min(40, week));
  return PREGNANCY_WEEKS[safeWeek - 1] || PREGNANCY_WEEKS[PREGNANCY_WEEKS.length - 1];
}
